# Generated by Django 4.2.4 on 2024-02-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50, verbose_name='Имя отправителя')),
                ('dispatch_time', models.DateTimeField(verbose_name='Время отправки')),
                ('payload', models.CharField(max_length=320, verbose_name='Полезная нагрузка')),
            ],
        ),
    ]
